# Generated by Django 2.2.4 on 2021-05-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(default='--', max_length=225),
            preserve_default=False,
        ),
    ]
