# Generated by Django 2.2.4 on 2021-05-29 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0004_auto_20210524_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='desc',
            new_name='description',
        ),
    ]
